# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
    node-install:
        docker:
          - image: cimg/base:stable
        steps:
          - node/install-packages
workflows:
  workflow:
    jobs:
      - node-install
      - node/run